package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class PrimEscController {
	@FXML
	private Button Button1;
	@FXML
	private Button Button2;

	// Event Listener on Button[#Button1].onAction
	@FXML
	public void Agregar(ActionEvent event) {
		// TODO Autogenerated
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("SegEsc.fxml"));
	        Parent root = loader.load(); // cargo la escena
			
	        //TerSceController TresController = loader.getController();
	        //TresController.setPersona(selectedPerson);
	        
	        Scene scene = new Scene(root);
			Stage stage= new Stage();
		    stage.setScene(scene);
		    stage.show();
		    Stage currentStage = (Stage) Button1.getScene().getWindow();
	        currentStage.close();
		 } catch (IOException e) {
			 e.printStackTrace();
		 }
	}
	// Event Listener on Button[#Button2].onAction
	@FXML
	public void Consultar(ActionEvent event) {
		// TODO Autogenerated
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("TercEsc.fxml"));
	        Parent root = loader.load(); // cargo la escena
			
	        //TerSceController TresController = loader.getController();
	        //TresController.setPersona(selectedPerson);
	        
	        Scene scene = new Scene(root);
			Stage stage= new Stage();
		    stage.setScene(scene);
		    stage.show();
		    Stage currentStage = (Stage) Button2.getScene().getWindow();
	        currentStage.close();
		 } catch (IOException e) {
			 e.printStackTrace();
		 }
	}
}
